In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-1.33068592,  1.81108754, -0.73822391,  1.08651172, -0.06699873,
        0.23287774,  0.58396104, -0.88569344,  0.07847531, -0.85484508])

In [7]:
B = np.random.randn(10)
B

array([ 1.05807199, -0.88668409, -0.38463083,  0.49374056, -1.28934667,
       -0.27639233,  0.35463581, -0.37472664, -0.63708955, -0.19307917])

In [8]:
# Binary Functions
np.add(A,B)

array([-0.27261394,  0.92440345, -1.12285474,  1.58025228, -1.3563454 ,
       -0.04351459,  0.93859686, -1.26042009, -0.55861424, -1.04792425])

In [9]:
np.maximum(A,B)


array([ 1.05807199,  1.81108754, -0.38463083,  1.08651172, -0.06699873,
        0.23287774,  0.58396104, -0.37472664,  0.07847531, -0.19307917])

In [11]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True